spring.application.name=multipledb
#spring.jpa.defer-datasource-initialization=true
logging.level.org.springframework.boot.context.config=DEBUG

# employeedb
spring.employee.datasource.url=jdbc:postgresql://localhost:5432/EmployeeDB
spring.employee.datasource.username=postgres
spring.employee.datasource.password=sc123ytd
spring.employee.datasource.driver-class-name=org.postgresql.Driver
spring.employee.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# salarydb
spring.salary.datasource.url=jdbc:postgresql://localhost:5432/SalaryDB
spring.salary.datasource.username=postgres
spring.salary.datasource.password=sc123ytd
spring.salary.datasource.driver-class-name=org.postgresql.Driver
spring.salary.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql=true